pip install requests
pip install bs4
pip install os
pip install sys
pip install folium
pip install threading
pip install time
pip install random
pip install datetime
pip install sys
pip install argparse
pip install colorama
pip install tkinter
pip install base64
